name: build QtUtility

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
        qt_version: ["6.3.0"]
        include:
          - os: ubuntu-latest
            cpp_compiler: gcc
          - os: macos-latest
            cpp_compiler: clang
          - os: windows-latest
            cpp_compiler: msvc

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_version }}

    - name: Setup (Ubuntu)
      if: startsWith (matrix.os, 'ubuntu')
      run: sudo apt-get install libxkbcommon-dev libgl1-mesa-dev

    - name: Setup VS tools (Windows)
      if: startsWith (matrix.os, 'windows')
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}/app

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    # - name: Test
    #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
    #   run: ctest --build-config ${{ matrix.build_type }}
